CC := gcc

task1 :
	$(CC) -c main_01.c
	$(CC) main_01.o -o main_01.exe
	./main_01.exe

task2 :
	$(CC) -c main_02.c
	$(CC) main_02.o -o main_02.exe
	./main_02.exe

task3 :
	$(CC) -c main_03.c
	$(CC) main_03.o -o main_03.exe
	./main_03.exe

task4 :
	$(CC) -c main_04.c
	$(CC) main_04.o -o main_04.exe
	./main_04.exe

task5 :
	$(CC) -c main_05.c
	$(CC) main_05.o -o main_05.exe
	./main_05.exe

clean:
	$(RM) -rf *.exe *.o

